"""empty message

Revision ID: c85dc563c63f
Revises: 2e3bbe91989d
Create Date: 2020-05-20 16:52:45.510596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85dc563c63f'
down_revision = '2e3bbe91989d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('datetime', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'datetime')
    # ### end Alembic commands ###
